# install-services.yml

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Install apache
        yum: name=httpd state=present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Ensure the services are started 
        service: name=httpd state=started enabled=yes

      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=on'

      - name: restart apache
        service: name=httpd state=restarted